export interface Product {
  id: number
  name: string
  slug: string
  description: string
  price: number
  image: string
  category: string
  rating: number
  isNew?: boolean
  featured?: boolean
  discount: number
  sku: string
  weight?: string
  dietary?: string[]
}

export const products: Product[] = [
  {
    id: 1,
    name: "Chocolate Truffle Cake",
    slug: "chocolate-truffle-cake",
    description: "Cadbury delight enrobed in rich creamy chocolate glaze, ready to make your occasion cheerful.",
    price: 4200,
    image: "/images/products/cadbury-cake.webp",
    category: "Cakes",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "CAKE001",
    weight: "2 lb",
  },
  {
    id: 2,
    name: "Caramel Cake",
    slug: "caramel-cake",
    description: "Caramel cake with crunchy meringue layering topped with whipped cream.",
    price: 2000,
    image: "/images/products/caramel-crunch.webp",
    category: "Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE002",
    weight: "2 lb",
  },
  {
    id: 3,
    name: "Salte Caramel Cake",
    slug: "salt-caramel-cake",
    description: "Sweet yet briny Caramel cake made with salt sprinkling on top of the concoction.",
    price: 5850,
    image: "/images/products/salte-caramel-cake.webp",
    category: "Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE003",
    weight: "2 lb",
  },
  {
    id: 4,
    name: "Nutella Cake",
    slug: "nutella-cake",
    description: "Soft, tender, and moist cake drenched in Nutella with dark chocolate frosting. The best match for your birthdays and Anniversary commemoration.",
    price: 5000,
    image: "/images/products/nutella-cake.webp",
    category: "Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE004",
    weight: "2 lb",
  },
  {
    id: 5,
    name: "Lotus Biscoff Cake",
    slug: "lotus-biscoff-cake",
    description: "An artisan buttercream and lotus biscoff crumbs cake, a perfect match for your birthday and anniversary celebrations.",
    price: 6000,
    image: "/images/products/lotus-cake.webp",
    category: "Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE005",
    weight: "2 lb",
  },
  {
    id: 6,
    name: "Honey Coffee Cake",
    slug: "honey-coffee-cake",
    description: "A thin layered honey filled dazzled cake in Coffee flavor fashioning the French aura in your dessert.",
    price: 7000,
    image: "/images/products/honey-coffee-cake.webp",
    category: "Cakes",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "CAKE006",
    weight: "2 lb",
  },
  {
    id: 7,
    name: "Chocolate Fudge",
    slug: "chocolate-fudge",
    description: "Our thick, rich taste and luscious chocolate fudge is an ideal blend of dark Chocolate, Cocoa powder, buttermilk, and a mighty fudge in the middle to give you an appetizing experience",
    price: 3900,
    image: "/images/products/choclate-fudge-cake.webp",
    category: "Cakes",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE007",
    weight: "2 lb",
  },
  {
    id: 8,
    name: "Cheesy Cake Per Slice",
    slug: "cheesy-cake-per-slice",
    description: "A Cheesy cake? Who’s going to say NO to our decadent and rich dessert?",
    price: 800,
    image: "/images/products/chese-cake-slice.webp",
    category: "Cakes",
    rating: 4,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE008",
  },
  {
    id: 9,
    name: "Opera Cake Per Slice",
    slug: "opera-cake-per-slice",
    description: "Our artiste opera cake made with almond coated sponge and potent coffee syrup has an origin in the french dessert world.",
    price: 600,
    image: "/images/products/opera-cake-slice.webp",
    category: "Cakes",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE009",
  },
  {
    id: 10,
    name: "Pink Wedding Cake",
    slug: "pink-wedding-cake",
    description: "Theme cakes for your destination weddings. Marvellous pink cake to make your occasion look adorable yet classy.",
    price: 50000,
    image: "/images/products/pink-wedding-cake.webp",
    category: "Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE010",
    weight: "8 lb",
  },
  {
    id: 11,
    name: "Galaxy Bonbon",
    slug: "galaxy-bonbon",
    description: "Especially crafted Chocolate Galaxy bonbons ready to take to out of this world with their deliciousness.",
    price: 1450,
    image: "/images/products/color-bonbons.webp",
    category: "Color Bonbon",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "BON001",
  },
  {
    id: 12,
    name: "Customized Cakes",
    slug: "customized-cakes",
    description: "Get your hands on our perfectly customized and premium cakes.",
    price: 10250,
    image: "/images/products/customized-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE011",
  },
  {
    id: 13,
    name: "Wedding Cake",
    slug: "wedding-cake",
    description: "To celebrate your best memories chocolate Academy brings you a premium Wedding cake series, to rejoice in the love and sparkle of your special day.",
    price: 22000,
    image: "/images/products/cus-wedding-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE012",
  },
  {
    id: 14,
    name: "Birthday Cake",
    slug: "birthday-cake",
    description: "Your birthday wish may not come true but your wish to have the world’s best cake on your birthday can come true. We wish you a day filled with merriment and a year full of excitement. Double the fun on your birthday with our personalized birthday cakes. Customize your cake according to your desire. Because joy lies within the bite of a cake.",
    price: 5850,
    image: "/images/products/cus-birthday-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE03",
  },
  {
    id: 15,
    name: "Autumn Girl Cake",
    slug: "autumn-girl-cake",
    description: "For autumn lovers, we bring autumn Girl cakes. Minimal cake with your favorite fillings inside and autumn leaves embellished on the top.",
    price: 1400,
    image: "/images/products/cus-autmn-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "CAKE015",
    weight: "4 lb",
  },
  {
    id: 16,
    name: "Baby Shower Cake",
    slug: "baby-shower-cake",
    description: "It’s time to celebrate the upcoming bliss with our cute customized baby shower cake, specially designed to put blessings beforehand.",
    price: 10000,
    image: "/images/products/cus-baby-shower-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE016",
    weight: "4 lb",
  },
  {
    id: 17,
    name: "Birthday Bear Cake",
    slug: "birthday-bear-cake",
    description: "Say yes to cute trendy Birthday cakes with colorful attractive layering and delicious sponge fillings inside.This anti-gravity cake is an absolute necessity.",
    price: 25000,
    image: "/images/products/cus-bear-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE017",
    weight: "8 lb",
  },
  {
    id: 18,
    name: "Cocomelon Cake",
    slug: "cocomelon-cake",
    description: "Rejoice your cocomelon kids with the best in town cocomelon cake with a cloud and rainbow theme.",
    price: 9750,
    image: "/images/products/cus-cocomelon-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "CAKE018",
    weight: "4 lb",
  },
  {
    id: 19,
    name: "Halloween Fun Cake",
    slug: "halloween-fun-cake",
    description: "Let’s break the traditional chain by adding some spooky delicious designer cakes to your halloween to do list.",
    price: 13650,
    image: "/images/products/cus-halloween-fun-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE019",
    weight: "4 lb",
  },
  {
    id: 20,
    name: "Honey Bee Cake",
    slug: "honey-bee-cake",
    description: "Hone your confection cravings with our personalized honey bee cake made to cherish your day-to-day events.",
    price: 10000,
    image: "/images/products/cus-honey-bee-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE020",
    weight: "4 lb",
  },
  {
    id: 21 ,
    name: "Maries Cake",
    slug: "maries-cake",
    description: "For the ultimate kitty lovers, we customized this amazing cake perfect for your kid’s birthday party. Call for a party.",
    price: 9000,
    image: "/images/products/cus-maries-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE021",
    weight: "3 lb",
  },
  {
    id: 22,
    name: "Pull Up The Bear Cake",
    slug: "pull-up-the-bear-cake",
    description: "What’s more exciting than a bear over a cute bear? Get this hot-selling piece of art enriched with the delicious fillings of your choice.",
    price: 13000,
    image: "/images/products/cus-pull-bear-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "CAKE022",
    weight: "3 lb",
  },
  {
    id: 23,
    name: "Rupenzel Cake",
    slug: "rupenzel-cake",
    description: "Straight from the rapunzel stories, this marvellous cake is no fiction. Get your cake for your rhyme queen today.",
    price: 18000,
    image: "/images/products/cus-rupenzel-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE023",
    weight: "6 lb",
  },
  {
    id: 24,
    name: "The Kettle Cake",
    slug: "the-kettle-cake",
    description: "For a bookaholic, this cake is a perfect match.",
    price: 40000,
    image: "/images/products/cus-kettle-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE024",
    weight: "8 lb",
  },
  {
    id: 25,
    name: "The Mermaid Cake",
    slug: "the-mermaid-cake",
    description: "The best pick for sea lovers. Get your hands on our marvellously personalized mermaid-style cake.",
    price: 5850,
    image: "/images/products/cus-mermaid-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE025",
    weight: "3 lb",
  },
  {
    id: 26,
    name: "The Swan Cake",
    slug: "the-swan-cake",
    description: "Crash your birthday party with this versatile Swan cake made with prudent flower toppings and ganache fillings.",
    price: 9750,
    image: "/images/products/cus-swan-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "CAKE026",
    weight: "3 lb",
  },
  {
    id: 27,
    name: "Tinker Bell Cake",
    slug: "tinker-bell-cake",
    description: "Explore the fantasy world with the exclusive range of disney cakes. Celebrate your favorite disney princess this birthday with us.",
    price: 9750,
    image: "/images/products/cus-tinker-bell-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE027",
    weight: "4 lb",
  },
  {
    id: 28,
    name: "Unicorn Cake",
    slug: "unicorn-cake",
    description: "Let us put magic in your upcoming event by getting this remarkable unicorn cake filled with mystic fillings.",
    price: 19500,
    image: "/images/products/cus-unicorn-cake.webp",
    category: "Customized Cakes",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "CAKE028",
    weight: "8 lb",
  },
  {
    id: 29,
    name: "Lilac Wedding Cake",
    slug: "lilac-wedding-cake",
    description: "Weddings are made with love and we are ready to shower elegance in it with our exclusive collection of the lilac palate.",
    price: 40000,
    image: "/images/products/cus-lilac-wedding-cake.webp",
    category: "Customized Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE029",
    weight: "15 lb",
  },
  {
    id: 30,
    name: "Chocolate Fun Factory",
    slug: "chocolate-fun-factory",
    description: "Get a sneak peek into the one-day chocolate workshop by making simple chocolate truffles, bonbons, novelties, and some baked stuff",
    price: 5000,
    image: "/images/products/fun-factory.webp",
    category: "Workshop",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "WORKSHOP001",
  },
  {
    id: 31,
    name: "Pizza Workshop",
    slug: "pizza-workshop",
    description: "Master the art of making different types of Italian flatbreads in this exclusive pizza workshop.",
    price: 3000,
    image: "/images/products/pizza-workshop.webp",
    category: "Workshop",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "WORKSHOP002",
  },
  {
    id: 32,
    name: "French Pastry Workshop",
    slug: "french-pastry-workshop",
    description: "Get your hands on the peeking chemistry of dough in a French aura by making the finest French pastries from scratch.",
    price: 25000,
    image: "/images/products/pastry-workshop.webp",
    category: "Workshop",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "WORKSHOP003",
  },
  {
    id: 33,
    name: "6 Bars In A Box",
    slug: "6-bars-in-a-box",
    description: "A protein bar is a healthy assortment and a good source of potassium, Vitamin B, fiber, Iron, and Calcium. These bars give you a dual advantage by helping you gain muscles and promoting weight loss. It can be your post-workout snack or a good meal replacement.",
    price: 4500,
    image: "/images/products/6-bars.webp",
    category: "Healthy Snacks",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "HEALTHY001",
},
{
  id: 34,
  name: "Banana Milk Chocolate",
  slug: "banana-milk-chocolate",
  description: "Your healthy and nutritious reserve of the day.",
  price: 850,
  image: "/images/products/banana-milk-chocolate.webp",
  category: "Healthy Snacks",
  rating: 4,
  isNew: false,
    featured: false,
    discount: 0,
    sku: "HEALTHY002",
},
{
  id: 35,
  name: "Banana Milk Chocolate",
  slug: "banana-milk-chocolate",
  description: "Your healthy and nutritious reserve of the day.",
  price: 850,
  image: "/images/products/banana-milk-chocolate2.webp",
  category: "Healthy Snacks",
  rating: 4,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "HEALTHY003",
},
{
  id: 36,
  name: "Banana Milk Chocolate",
  slug: "banana-milk-chocolate3",
  description: "Your healthy and nutritious reserve of the day.",
  price: 850,
  image: "/images/products/banana-milk-chocolate3.webp",
  category: "Healthy Snacks",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "HEALTHY004",
},
{
  id: 37,
  name: "Chocolate Bar Box",
  slug: "chocolate-bar-box",
  description: "A protein bar is a healthy assortment and a good source of potassium, Vitamin B, fiber, Iron, and Calcium. These bars give you a dual advantage by helping you gain muscles and promoting weight loss. It can be your post-workout snack or a good meal replacement.",
  price: 4500,
  image: "/images/products/chocolate-bar-box.webp",
  category: "Healthy Snacks",
  rating: 5,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "HEALTHY005",
},
{
  id: 38,
  name: "Dark Cashews",
  slug: "dark-cashews",
  description: "Salted cashews are perfectly molded in smooth velvety dark chocolate to make your everyday snack.",
  price: 850,
  image: "/images/products/dark-cashews.webp",
  category: "Healthy Snacks",
  rating: 4,
  isNew: true,
  featured: false,
  discount: 0,
  sku: "HEALTHY006",
},
{
  id: 39,
  name: "Biscotti",
  slug: "biscotti",
  description: "Sliced cookie cut into long dough pieces, baked, and re-baked to give the distinctive moist texture. Biscotti makes the perfect finger-shaped cookie.",
  price: 850,
  image: "/images/products/biscotti.webp",
  category: "Healthy Snacks",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "HEALTHY007",
},
{
  id: 40,
  name: "Protien Bars Four Pack",
  slug: "protien-bars-four-pack",
  description: "A protein bar is a healthy assortment and a good source of potassium, Vitamin B, fiber, Iron, and Calcium. These bars give you a dual advantage by helping you gain muscles and promoting weight loss. It can be your post-workout snack or a good meal replacement.",
  price: 1600,
  image: "/images/products/protein-bars-four.webp",
  category: "Healthy Snacks",
  rating: 4,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "HEALTHY008",
},
{
  id: 41,
  name: "Sugar Coated Nuts",
  slug: "sugar-coated-nuts",
  description: "Crunchy dissolved sugar coatings over nuts to give your snacking time a wonderful sweet candied nosh.",
  price: 1450,
  image: "/images/products/sugar-coated-nuts.webp",
  category: "Healthy Snacks",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "HEALTHY009",
},
{
  id: 42,
  name: "Chilli Coated Nuts",
  slug: "chilli-coated-nuts",
  description: "Hot and smoked Chile-coated nuts are the best fit for the gluten-free category. A hot blend of chilli with other herbs baked under low pressure to give a picante finish.",
  price: 1450,
  image: "/images/products/chilli-coated-nuts.webp",
  category: "Healthy Snacks",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "HEALTHY010",
},
{
  id: 43,
  name: "Hazelnut Fingers",
  slug: "hazelnut-fingers",
  description: "Finger-shaped cookies are made with baked hazelnuts, chocolate chips, purpose flour, espresso powder, and many other freshly extract ingredients to transpire an exclusive flavor and shape.",
  price: 850,
  image: "/images/products/hazelnut-fingers.webp",
  category: "Healthy Snacks",
  rating: 5,
  isNew: true,
  featured: true,
  discount: 0,
  sku: "HEALTHY011",
},
{
  id: 44,
  name: "Assorted Brownie Box",
  slug: "assorted-brownie-box",
  description: "Get a fine assortment of your favorite brownies collectively in a single meal box.",
  price: 1450,
  image: "/images/products/assorted-brownie-box.webp",
  category: "Brownies",
  rating: 5,
  isNew: true,
  featured: true,
  discount: 0,
  sku: "BROWNIE001",
},
{
  id: 45,
  name: "Black Premium Chocolate Box",
  slug: "black-premium-chocolate-box",
  description: "Exclusive Black Box with fusion bonbons to whisk the piquancy in sweetly seasoned and melted chocolate fillings with a shiny coating. (12 pcs)",
  price: 1450,
  image: "/images/products/black-premium-chocolate-box.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: true,
  featured: true,
  discount: 0,
  sku: "BON001",
},
{
  id: 46,
  name: "White Premium Chocolate Box",
  slug: "white-premium-chocolate-box",
  description: "Exclusive White Box with fusion bonbons to whisk the piquancy in sweetly seasoned and melted chocolate fillings with a shiny coating.",
  price: 1450,
  image: "/images/products/white-premium-chocolate-box.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "BON002",
},
{
  id: 47 ,
  name: "Coloured Chocolate Box",
  slug: "coloured-chocolate-box",
  description: "Fusion bonbons to whisk the piquancy in sweetly seasoned and melted chocolate fillings with a shiny coating.",
  price: 1450,
  image: "/images/products/coloured-chocolate-box.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON003",
},
{
  id: 48,
  name: "Sugar And Spice",
  slug: "sugar-and-spice",
  description: "Fusion bonbons to whisk the piquancy in sweetly seasoned and melted chocolate fillings with a shiny coating.",
  price: 1450,
  image: "/images/products/sugar-and-spice.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "BON004",
},
{
  id: 49,
  name: "Dark Drip",
  slug: "dark-drip",
  description: "Syrupy condensed milk bonbons dipped in tempered chocolate to make a dark velvety texture.",
  price: 1450,
  image: "/images/products/dark-drip.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: true,
  featured: false,
  discount: 0,
  sku: "BON005",
},
{
  id: 50,
  name: "Orange Rush",
  slug: "orange-rush",
  description: "Hand-crafted fruity bonbons, ready to vivify your day with its orange exclusive artisan flavor.",
  price: 1450,
  image: "/images/products/orange-rush.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON006",
},
{
  id: 51,
  name: "Deep Mint",
  slug: "deep-mint",
  description: "A luxurious blend of mint with hot chocolate to rouse a refined seasonal flavor in your bonbon treat.",
  price: 1450,
  image: "/images/products/deep-mint.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "BON007",
},
{
  id: 52,
  name: "Orange Cream",
  slug: "orange-cream",
  description: "Mighty and creamy bonbons made with powdered orange drink, bittersweet chocolate, and vanilla ice cream.",
  price: 1450,
  image: "/images/products/orange-cream.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON008",
},
{
  id: 53,
  name: "Coffee",
  slug: "coffee",
  description: "For the love of coffee, we made you glazed bonbons with unsweetened chocolate to upsurge your coffee cravings.",
  price: 1450,
  image: "/images/products/coffee.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON009",
},
{
  id: 54,
  name: "Nutty Nut",
  slug: "nutty-nut",
  description: "Amassed nutty butter dipped in dark milk chocolate swirls the waggy texture of our hot-selling nutty nut bonbons.",
  price: 1450,
  image: "/images/products/nutty-nut.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: true,
  featured: true,
  discount: 0,
  sku: "BON010",
},
{
  id: 55,
  name: "Sugar And Spice",
  slug: "sugar-and-spice2",
  description: "Fusion bonbons to whisk the piquancy in sweetly seasoned and melted chocolate fillings with a shiny coating.",
  price: 1450,
  image: "/images/products/sugar-and-spice2.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "BON011",
},
{
  id: 56,
  name: "Dark Drip",
  slug: "dark-drip2",
  description: "Syrupy condensed milk bonbons dipped in tempered chocolate to make a dark velvety texture.",
  price: 1450,
  image: "/images/products/dark-drip2.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON012",
},
{
  id: 57,
  name: "Orange Rush",
  slug: "orange-rush2",
  description: "Hand-crafted fruity bonbons, ready to vivify your day with its orange exclusive artisan flavor.",
  price: 1450,
  image: "/images/products/orange-rush2.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON013",
},
{
  id: 58,
  name: "Deep Mint",
  slug: "deep-mint2",
  description: "A luxurious blend of mint with hot chocolate to rouse a refined seasonal flavor in your bonbon treat.",
  price: 1400,
  image: "/images/products/deep-mint2.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: true,
  featured: false,
  discount: 0,
  sku: "BON014",
},
{
  id: 59,
  name: "Orange Cream",
  slug: "orange-cream2",
  description: "Mighty and creamy bonbons made with powdered orange drink, bittersweet chocolate, and vanilla ice cream.",
  price: 1450,
  image: "/images/products/orange-cream2.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: true,
  discount: 0,
  sku: "BON015",
},
{
  id: 60,
  name: "Coffee",
  slug: "coffee2",
  description: "For the love of coffee, we made you glazed bonbons with unsweetened chocolate to upsurge your coffee cravings.",
  price: 1450,
  image: "/images/products/coffee2.webp",
  category: "Chocolate Bonbons",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON016",
},
{
  id: 61,
  name: "Nutty Nut",
  slug: "nutty-nut2",
  description: "Amassed nutty butter dipped in dark milk chocolate swirls the waggy texture of our hot-selling nutty nut bonbons.",
  price: 1450,
  image: "/images/products/nutty-nut2.webp",
  category: "Chocolate Bonbons",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BON017",
},
{
id: 62,
name: "Roasted Almond Bar",
slug: "roasted-almond-bar",
description: "Creamy milk chocolate with baked almond crumps assembled to make a roasted almond bar.",
price: 900,
image: "/images/products/roasted-almond-bar.webp",
category: "Bar Tablets",
rating: 5,
isNew: false,
featured: true,
discount: 0,
sku: "BAR001",
},
{
id: 63,
name: "Dark Orange",
slug: "dark-orange",
description: "Rich, refined and luxurious chocolate bar infused with bracing dark orange under the supervision of our master chocolate chefs.",
price: 850,
image: "/images/products/dark-orange.webp",
category: "Bar Tablets",
rating: 4,
isNew: false,
featured: false,
discount: 0,
sku: "BAR002",
},
{
id: 64,
name: "Caramel Glazed",
slug: "caramel-glazed",
description: "Dark chocolate coated bar with tempting glaze caramel inside to make your caramel glazed treat, perfect for gifting.",
price: 850,
image: "/images/products/caramel-glazed.webp",
category: "Bar Tablets",
rating: 5,
isNew: false,
featured: false,
discount: 0,
sku: "BAR003",
},
{
  id: 65,
  name: "Dark Chocolate Nutty Bark",
  slug: "dark-chocolate-nutty-bark",
  description: "Craggy nuts dipped in dark milk chocolate crafted in a jagged texture of thin bark.",
  price: 1000,
  image: "/images/products/dark-chocolate-nutty-bark.webp",
  category: "Chocolate Barks",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "BARK001",
  },
  
{
  id: 66,
  name: "Birthday Cake",
  slug: "birthday-cake",
  description: "Rejoice on your birthday with the best of all, chocolate academy’s customized birthday cake collection. Because we believe in customer’s preferences.",
  price: 5850,
  image: "/images/products/birthday-cake.webp",
  category: "Minimalistic Cakes",
  rating: 4,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "MINI001",
  weight: "3 lb",
},
{
  id: 67,
  name: "Black Floral Cake",
  slug: "black-floral-cake",
  description: "A fair chunk of black gateau to make your everyday celebration memorable.",
  price: 7000,
  image: "/images/products/black-floral-cake.webp",
  category: "Minimalistic Cakes",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "MINI002",
  weight: "3 lb",
},
{
id: 68,
name: "Green Floral Cake",
slug: "green-floral-cake",
description: "A lovely floral pie glazed with green royal coating, with tender sponge dripping in creamy and chocolaty fillings.",
price: 7000,
image: "/images/products/green-floral-cake.webp",
category: "Minimalistic Cakes",
rating: 5,
isNew: false,
featured: true,
discount: 0,
sku: "MINI003",
weight: "3 lb",
},
{
id: 69,
name: "Mermaid Cake",
slug: "mermaid-cake",
description: "The best pick for sea lovers. Get your hands on our marvellously personalized mermaid-style cake.",
price: 11700,
image: "/images/products/mermaid-cake.webp",
category: "Minimalistic Cakes",
rating: 4,
isNew: false,
featured: false,
discount: 0,
sku: "MINI004",
weight: "3 lb",
},
{
id: 70,
name: "Pastel Passion Cake",
slug: "pastel-passion-cake",
description: "Trendy pastel-style minimal cakes are perfectly made to add elegance and grace.",
price: 12750,
image: "/images/products/pastel-passion-cake.webp",
category: "Minimalistic Cakes",
rating: 5,
isNew: false,
featured: false,
discount: 0,
sku: "MINI005",
weight: "3 lb",
},
{
  id: 71,
  name: "White Floral Cake",
  slug: "white-floral-cake",
  description: "Minimalism and simplicity combined together with the tempting flavor intermixed with imported white flowers on top of it.",
  price: 9850,
  image: "/images/products/white-floral-cake.webp",
  category: "Minimalistic Cakes",
  rating: 5,
  isNew: false,
  featured: false,
  discount: 0,
  sku: "MINI006",
  weight: "3 lb",
  },
  {
    id: 72,
    name: "Macron Box 4 Pcs",
    slug: "macron-box-4-pcs",
    description: "One macron? No, a lot of macrons. Get your assorted macron box filled with delight today. Have a sweet day!",
    price: 1000,
    image: "/images/products/macron-box-4-pcs.webp",
    category: "Macrons",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "MAC001",
    },

  ]
