export interface Product {
  id: number
  name: string
  slug: string
  description: string
  price: number
  image: string
  category: string
  rating: number
  isNew?: boolean
  featured?: boolean
  discount: number
  sku: string
  weight?: string
  dietary?: string[]
}

export const products: Product[] = [
  {
    id: 1,
    name: "Chocolate Truffle Cake",
    slug: "chocolate-truffle-cake",
    description: "Rich and decadent chocolate truffle cake with a smooth ganache finish.",
    price: 2500,
    image: "/images/products/cake1.png",
    category: "Cakes",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "CAKE001",
    weight: "1 kg",
    dietary: ["Vegetarian"],
  },
  {
    id: 2,
    name: "Caramel Cake",
    slug: "caramel-cake",
    description: "Delicious caramel cake with caramel drizzle and buttercream frosting.",
    price: 2800,
    image: "/images/products/cake2.png",
    category: "Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 10,
    sku: "CAKE002",
    weight: "1 kg",
  },
  {
    id: 3,
    name: "Lotus Biscoff Cake",
    slug: "lotus-biscoff-cake",
    description: "Delightful cake with layers of Lotus Biscoff spread and crushed cookies.",
    price: 3000,
    image: "/images/products/cake3.png",
    category: "Cakes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "CAKE003",
    weight: "1 kg",
  },
  {
    id: 4,
    name: "Honey Coffee Cake",
    slug: "honey-coffee-cake",
    description: "A perfect blend of honey and coffee flavors in a moist and fluffy cake.",
    price: 2800,
    image: "/images/products/cake4.png",
    category: "Cakes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "CAKE004",
    weight: "1 kg",
  },
  {
    id: 5,
    name: "Sugar and Spice Bonbon",
    slug: "sugar-and-spice-bonbon",
    description: "Handcrafted chocolate bonbon with a delightful sugar and spice filling.",
    price: 650,
    image: "/images/products/bonbon1.png",
    category: "Chocolate Bonbons",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "BON001",
    weight: "15g per piece",
    dietary: ["Vegetarian"],
  },
  {
    id: 6,
    name: "Orange Bliss Bonbon",
    slug: "orange-bliss-bonbon",
    description: "Exquisite chocolate bonbon with a refreshing orange-infused ganache.",
    price: 650,
    image: "/images/products/bonbon2.png",
    category: "Chocolate Bonbons",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "BON002",
    weight: "15g per piece",
  },
  {
    id: 7,
    name: "Coffee Bonbon",
    slug: "coffee-bonbon",
    description: "Rich chocolate bonbon with a smooth coffee ganache center.",
    price: 650,
    image: "/images/products/bonbon3.png",
    category: "Chocolate Bonbons",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "BON003",
    weight: "15g per piece",
    dietary: ["Vegetarian"],
  },
  {
    id: 8,
    name: "Nutty Nut Bonbon",
    slug: "nutty-nut-bonbon",
    description: "Delicious chocolate bonbon filled with a nutty praline center.",
    price: 650,
    image: "/images/products/bonbon4.png",
    category: "Chocolate Bonbons",
    rating: 4,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "BON004",
    weight: "15g per piece",
    dietary: ["Contains Nuts"],
  },
  {
    id: 9,
    name: "Dark Chocolate Bar",
    slug: "dark-chocolate-bar",
    description: "Premium dark chocolate bar made with 70% cocoa for an intense chocolate experience.",
    price: 850,
    image: "/images/products/bar1.png",
    category: "Chocolate Bars",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "BAR001",
    weight: "100g",
    dietary: ["Vegan", "Gluten Free"],
  },
  {
    id: 10,
    name: "Milk Chocolate Bar",
    slug: "milk-chocolate-bar",
    description: "Smooth and creamy milk chocolate bar made with the finest ingredients.",
    price: 750,
    image: "/images/products/bar2.png",
    category: "Chocolate Bars",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 5,
    sku: "BAR002",
    weight: "100g",
  },
  {
    id: 11,
    name: "Hazelnut Chocolate Bar",
    slug: "hazelnut-chocolate-bar",
    description: "Delicious milk chocolate bar with crunchy hazelnut pieces.",
    price: 950,
    image: "/images/products/bar3.png",
    category: "Chocolate Bars",
    rating: 5,
    isNew: true,
    featured: true,
    discount: 0,
    sku: "BAR003",
    weight: "100g",
    dietary: ["Contains Nuts"],
  },
  {
    id: 12,
    name: "Luxury Chocolate Gift Box",
    slug: "luxury-chocolate-gift-box",
    description: "An elegant assortment of our finest chocolates presented in a beautiful gift box.",
    price: 3500,
    image: "/images/products/gift1.png",
    category: "Gift Boxes",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "GIFT001",
    weight: "250g",
    dietary: ["Mixed"],
  },
  {
    id: 13,
    name: "Assorted Truffles Box",
    slug: "assorted-truffles-box",
    description: "A delightful collection of handcrafted chocolate truffles in various flavors.",
    price: 2200,
    image: "/images/products/gift2.png",
    category: "Gift Boxes",
    rating: 4,
    isNew: false,
    featured: false,
    discount: 15,
    sku: "GIFT002",
    weight: "200g",
  },
  {
    id: 14,
    name: "Chocolate Brownies",
    slug: "chocolate-brownies",
    description: "Rich and fudgy chocolate brownies made with premium cocoa.",
    price: 1200,
    image: "/images/products/brownie1.png",
    category: "Brownies",
    rating: 5,
    isNew: false,
    featured: false,
    discount: 0,
    sku: "BROWN001",
    weight: "Pack of 6",
    dietary: ["Vegetarian"],
  },
  {
    id: 15,
    name: "Walnut Brownies",
    slug: "walnut-brownies",
    description: "Decadent chocolate brownies loaded with crunchy walnuts.",
    price: 1400,
    image: "/images/products/brownie2.png",
    category: "Brownies",
    rating: 4,
    isNew: true,
    featured: false,
    discount: 0,
    sku: "BROWN002",
    weight: "Pack of 6",
    dietary: ["Contains Nuts"],
  },
  {
    id: 16,
    name: "Birthday Chocolate Hamper",
    slug: "birthday-chocolate-hamper",
    description: "Special birthday hamper filled with an assortment of chocolates and treats.",
    price: 4500,
    image: "/images/products/hamper1.png",
    category: "Hampers",
    rating: 5,
    isNew: false,
    featured: true,
    discount: 0,
    sku: "HAMP001",
    weight: "500g",
  },
]
